### ISSUE TITLE
Connection break after 8 hours when system is ideal.

### ISSUE THREAD

**Issue by somesh9827** [ActiveJpa/activejpa#31]
Hey I am using Dropwizard with activeJPA.

My connection from mysql db closed after 8 hours if system is ideal.

Please solve this issue.

**Comment by ganeshs** [comment]
Somesh, this should be an issue with your connection pool settings. You
will have to set idle test period in your configuration.

**Comment by vamsi-subhash** [comment]
Ex:
in dropwizard, you need to
​set:
​
maxWaitForConnection: 10s
evictionInterval: 10s
maxConnectionAge: 108000s
*minIdleTime: 1 minute*

​for tomcat JDBC connection pool.​


On Mon, Aug 3, 2015 at 3:33 PM, Ganesh Subramanian <notifications@github.com
> wrote:

> Somesh, this should be an issue with your connection pool settings. You
> will have to set idle test period in your configuration.
> On Aug 3, 2015 3:13 PM, "Somesh Shrivastava" <notifications@github.com>
> wrote:
>
> > Hey I am using Dropwizard with activeJPA.
> >
> > My connection from mysql db closed after 8 hours if system is ideal.
> >
> > Please solve this issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ActiveJpa/activejpa/issues/31>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ActiveJpa/activejpa/issues/31#issuecomment-127182558>.
>



-- 
Regards
Vamsi Subhash

-- 


------------------------------------------------------------------------------------------------------------------------------------------

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited. Although Flipkart has taken reasonable precautions to ensure no 
viruses are present in this email, the company cannot accept responsibility 
for any loss or damage arising from the use of this email or attachments

**Comment by ganeshs** [comment]
Closing as its not an issue
