### ISSUE TITLE
Error retrieving information after merge or persist

### ISSUE THREAD

**Issue by alejandradaquino** [ActiveJpa/activejpa#34]
I have my application with spring boot, when I persist an entity modified to the database (with merge or persist), seems not to be updating the cache for threads, I think that because in the database layer the information is updated correctly but refreshing the info from the frontend, sometimes gets the previous version and sometimes the  new version and the sql query is logged all the times

**Comment by alejandradaquino** [comment]
This code print diferent output each excecution
```
userRelations = Circle.getUsersCircleRelations(this.getId());
		userRelations.stream().forEach(relation -> System.out.println(relation.getType().toString()));
```
		

`Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
PARTICIPANT
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
ADMINISTRATOR
Hibernate: select circle1_.id as id1_2_, circle1_.name as name2_2_, circle1_.theme as theme3_2_ from user_circle_relation usercircle0_ inner join circle circle1_ on usercircle0_.circle_id=circle1_.id where usercircle0_.user_id=?
Hibernate: select usercircle0_.id as id1_4_, usercircle0_.circle_id as circle_i3_4_, usercircle0_.type as type2_4_, usercircle0_.user_id as user_id4_4_ from user_circle_relation usercircle0_ where usercircle0_.circle_id=?
ADMINISTRATOR
PARTICIPANT`

**Comment by ganeshs** [comment]
@alejandradaquino ActiveJPA doesn't interfere in caching. I suspect that the entity manager is not closed  after the request completion. This could result in the thread serving the same entity manager for the next call resulting in data served from first level cache.

You will have to explicitly close the session or use org.activejpa.utils.OpenSessionInViewFilter as a filter to close the entitymanager after each request.

If you are using threads (or threadpools), you should be using org.activejpa.utils.ActiveJpaThreadFactory to do the cleaning up for you.

Let me know if it doesn't help

**Comment by alejandradaquino** [comment]
Hi @ganeshs!! I am trying with that, it makes sense...  Thanks for your support!
