### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by NetoDevel** [ActiveJpa/activejpa#36]
Could you provide me with a clean maven project only with jpa without using spring boot or another framework?

**Comment by ganeshs** [comment]
@NetoDevel Apologies for reverting back late. The documentation has listed down the steps to start using ActiveJPA for a vanilla application. Did you face any issues while following the steps? I will sure put up a simple example as well.

**Comment by ganeshs** [comment]
@NetoDevel I have put up a vanilla application under the examples  https://github.com/ActiveJpa/activejpa/tree/master/activejpa-examples/activejpa-examples-vanilla
