### ISSUE TITLE
Pagination & sortFields cannot be applied to a cloned filter

### ISSUE THREAD

**Issue by devesh04** [ActiveJpa/activejpa#42]
If the original filter doesn't have pagination properties ( `pageNo`, `perPage` ), 
there is no way to apply pagination properties in the cloned filter as `shouldPage` is not getting  updated while setting pageNo/perPage.

Also, cloning a filter doesn't consider `sortFields`. 
In earlier versions, getter of sortFields was public which was a workaround for it.

Please let me know if these should be incorporated, I can raise a quick PR for the same.

**Comment by ganeshs** [comment]
@devesh04 should be available in the next release

**Comment by ganeshs** [comment]
Available in 1.1.0. Closing this
